#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  sym_tree_sitter_word = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  aux_sym_binding_token1 = 8,
  anon_sym_COMMA = 9,
  anon_sym_DOT = 10,
  anon_sym_LPAREN2 = 11,
  aux_sym_call_on_literal_token1 = 12,
  sym_literal = 13,
  sym_word = 14,
  sym_symbol = 15,
  sym_source_file = 16,
  sym__sequence = 17,
  aux_sym__break = 18,
  sym__expr = 19,
  sym_group = 20,
  sym_pipe = 21,
  sym_binding = 22,
  sym__expr_binding = 23,
  sym_comma_group = 24,
  sym__expr_comma_group = 25,
  sym_call = 26,
  sym__expr_call = 27,
  sym_dot_pipe = 28,
  sym__expr_dot_pipe = 29,
  sym_no_space_call = 30,
  sym__expr_no_space_call = 31,
  sym_immediate_group = 32,
  sym_call_on_literal = 33,
  sym__expr_call_on_literal = 34,
  aux_sym__sequence_repeat1 = 35,
  aux_sym_comma_group_repeat1 = 36,
  aux_sym_comma_group_repeat2 = 37,
  aux_sym_call_repeat1 = 38,
  aux_sym_dot_pipe_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_tree_sitter_word] = "tree_sitter_word",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_binding_token1] = "binding_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN2] = "(",
  [aux_sym_call_on_literal_token1] = "literal",
  [sym_literal] = "literal",
  [sym_word] = "word",
  [sym_symbol] = "symbol",
  [sym_source_file] = "source_file",
  [sym__sequence] = "_sequence",
  [aux_sym__break] = "_break",
  [sym__expr] = "_expr",
  [sym_group] = "group",
  [sym_pipe] = "pipe",
  [sym_binding] = "binding",
  [sym__expr_binding] = "_expr_binding",
  [sym_comma_group] = "group",
  [sym__expr_comma_group] = "_expr_comma_group",
  [sym_call] = "call",
  [sym__expr_call] = "_expr_call",
  [sym_dot_pipe] = "pipe",
  [sym__expr_dot_pipe] = "_expr_dot_pipe",
  [sym_no_space_call] = "call",
  [sym__expr_no_space_call] = "_expr_no_space_call",
  [sym_immediate_group] = "group",
  [sym_call_on_literal] = "call",
  [sym__expr_call_on_literal] = "_expr_call_on_literal",
  [aux_sym__sequence_repeat1] = "_sequence_repeat1",
  [aux_sym_comma_group_repeat1] = "comma_group_repeat1",
  [aux_sym_comma_group_repeat2] = "comma_group_repeat2",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_dot_pipe_repeat1] = "dot_pipe_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_tree_sitter_word] = sym_tree_sitter_word,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_binding_token1] = aux_sym_binding_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [aux_sym_call_on_literal_token1] = sym_literal,
  [sym_literal] = sym_literal,
  [sym_word] = sym_word,
  [sym_symbol] = sym_symbol,
  [sym_source_file] = sym_source_file,
  [sym__sequence] = sym__sequence,
  [aux_sym__break] = aux_sym__break,
  [sym__expr] = sym__expr,
  [sym_group] = sym_group,
  [sym_pipe] = sym_pipe,
  [sym_binding] = sym_binding,
  [sym__expr_binding] = sym__expr_binding,
  [sym_comma_group] = sym_group,
  [sym__expr_comma_group] = sym__expr_comma_group,
  [sym_call] = sym_call,
  [sym__expr_call] = sym__expr_call,
  [sym_dot_pipe] = sym_pipe,
  [sym__expr_dot_pipe] = sym__expr_dot_pipe,
  [sym_no_space_call] = sym_call,
  [sym__expr_no_space_call] = sym__expr_no_space_call,
  [sym_immediate_group] = sym_group,
  [sym_call_on_literal] = sym_call,
  [sym__expr_call_on_literal] = sym__expr_call_on_literal,
  [aux_sym__sequence_repeat1] = aux_sym__sequence_repeat1,
  [aux_sym_comma_group_repeat1] = aux_sym_comma_group_repeat1,
  [aux_sym_comma_group_repeat2] = aux_sym_comma_group_repeat2,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_dot_pipe_repeat1] = aux_sym_dot_pipe_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_tree_sitter_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_binding_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_call_on_literal_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sequence] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__break] = {
    .visible = false,
    .named = false,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_binding] = {
    .visible = false,
    .named = true,
  },
  [sym_comma_group] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_comma_group] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_call] = {
    .visible = false,
    .named = true,
  },
  [sym_dot_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_dot_pipe] = {
    .visible = false,
    .named = true,
  },
  [sym_no_space_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_no_space_call] = {
    .visible = false,
    .named = true,
  },
  [sym_immediate_group] = {
    .visible = true,
    .named = true,
  },
  [sym_call_on_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_call_on_literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_group_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dot_pipe_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_fn = 1,
  field_id = 2,
  field_input = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fn] = "fn",
  [field_id] = "id",
  [field_input] = "input",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_fn, 0},
    {field_input, 1},
  [2] =
    {field_id, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_group,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_call_repeat1, 2,
    aux_sym_call_repeat1,
    sym_group,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
};

static inline bool anon_sym_LF_character_set_1(int32_t c) {
  return (c < 8232
    ? (c < 160
      ? (c < ' '
        ? (c >= '\t' && c <= '\r')
        : c <= ' ')
      : (c <= 160 || (c < 8192
        ? c == 5760
        : c <= 8202)))
    : (c <= 8233 || (c < 12288
      ? (c < 8287
        ? c == 8239
        : c <= 8287)
      : (c <= 12288 || c == 65279))));
}

static inline bool aux_sym_binding_token1_character_set_1(int32_t c) {
  return (c < 8192
    ? (c < ' '
      ? (c < 11
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || (c < 5760
        ? c == 160
        : c <= 5760)))
    : (c <= 8202 || (c < 8287
      ? (c < 8239
        ? (c >= 8232 && c <= 8233)
        : c <= 8239)
      : (c <= 8287 || (c < 65279
        ? c == 12288
        : c <= 65279)))));
}

static inline bool sym_symbol_character_set_1(int32_t c) {
  return (c < '<'
    ? (c < '*'
      ? (c < '#'
        ? c == '!'
        : c <= '&')
      : (c <= '+' || (c < '/'
        ? c == '-'
        : c <= '/')))
    : (c <= '@' || (c < '|'
      ? (c < '^'
        ? c == '\\'
        : c <= '^')
      : (c <= '|' || c == '~'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(23);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(7)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (aux_sym_binding_token1_character_set_1(lookahead)) ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 2:
      if (aux_sym_binding_token1_character_set_1(lookahead)) ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 4:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(8)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 5:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(6)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 6:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(6)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(23);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(7)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(8)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_binding_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_call_on_literal_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_symbol);
      if (sym_symbol_character_set_1(lookahead)) ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_tree_sitter_word] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_binding_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [aux_sym_call_on_literal_token1] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(64),
    [sym__sequence] = STATE(66),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(50),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(50),
    [sym_comma_group] = STATE(50),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [2] = {
    [aux_sym__break] = STATE(37),
    [sym__expr] = STATE(55),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(55),
    [sym_comma_group] = STATE(55),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [3] = {
    [aux_sym__break] = STATE(37),
    [sym__expr] = STATE(55),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(55),
    [sym_comma_group] = STATE(55),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [4] = {
    [aux_sym__break] = STATE(37),
    [sym__expr] = STATE(55),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(55),
    [sym_comma_group] = STATE(55),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [5] = {
    [sym__sequence] = STATE(62),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(50),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(50),
    [sym_comma_group] = STATE(50),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [6] = {
    [sym__sequence] = STATE(63),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(50),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(50),
    [sym_comma_group] = STATE(50),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [7] = {
    [sym__sequence] = STATE(65),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(50),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(50),
    [sym_comma_group] = STATE(50),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [8] = {
    [aux_sym__break] = STATE(37),
    [sym__expr] = STATE(55),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(55),
    [sym_comma_group] = STATE(55),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [9] = {
    [aux_sym__break] = STATE(37),
    [sym__expr] = STATE(47),
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym_binding] = STATE(47),
    [sym_comma_group] = STATE(47),
    [sym__expr_comma_group] = STATE(58),
    [sym_call] = STATE(53),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(43),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(35),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(22),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(15),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_literal] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
  },
  [10] = {
    [sym_group] = STATE(23),
    [sym_pipe] = STATE(23),
    [sym__expr_comma_group] = STATE(52),
    [sym_call] = STATE(52),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(42),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(34),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(23),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(25),
    [sym_literal] = ACTIONS(27),
    [sym_word] = ACTIONS(27),
  },
  [11] = {
    [sym_group] = STATE(23),
    [sym_pipe] = STATE(23),
    [sym__expr_comma_group] = STATE(52),
    [sym_call] = STATE(52),
    [sym__expr_call] = STATE(19),
    [sym_dot_pipe] = STATE(42),
    [sym__expr_dot_pipe] = STATE(60),
    [sym_no_space_call] = STATE(34),
    [sym__expr_no_space_call] = STATE(59),
    [sym_call_on_literal] = STATE(23),
    [sym__expr_call_on_literal] = STATE(61),
    [aux_sym_comma_group_repeat1] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(25),
    [sym_literal] = ACTIONS(27),
    [sym_word] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      aux_sym_call_repeat1,
    STATE(30), 1,
      sym_no_space_call,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(60), 1,
      sym__expr_dot_pipe,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(33), 2,
      sym_literal,
      sym_word,
    STATE(41), 2,
      sym__expr_call,
      sym_dot_pipe,
    STATE(25), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
    ACTIONS(31), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [43] = 11,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      aux_sym_call_repeat1,
    STATE(30), 1,
      sym_no_space_call,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(60), 1,
      sym__expr_dot_pipe,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(43), 2,
      sym_literal,
      sym_word,
    STATE(41), 2,
      sym__expr_call,
      sym_dot_pipe,
    STATE(25), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
    ACTIONS(35), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [86] = 15,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comma_group_repeat1,
    STATE(19), 1,
      sym__expr_call,
    STATE(27), 1,
      sym_no_space_call,
    STATE(40), 1,
      sym_dot_pipe,
    STATE(54), 1,
      sym_call,
    STATE(58), 1,
      sym__expr_comma_group,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(60), 1,
      sym__expr_dot_pipe,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(46), 2,
      sym_literal,
      sym_word,
    STATE(56), 2,
      sym__expr_binding,
      sym_comma_group,
    STATE(21), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
  [136] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      sym__expr_call,
    STATE(34), 1,
      sym_no_space_call,
    STATE(39), 1,
      aux_sym_comma_group_repeat1,
    STATE(42), 1,
      sym_dot_pipe,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(60), 1,
      sym__expr_dot_pipe,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(27), 2,
      sym_literal,
      sym_word,
    STATE(57), 2,
      sym__expr_comma_group,
      sym_call,
    STATE(23), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
  [180] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      sym__expr_call,
    STATE(34), 1,
      sym_no_space_call,
    STATE(39), 1,
      aux_sym_comma_group_repeat1,
    STATE(42), 1,
      sym_dot_pipe,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(60), 1,
      sym__expr_dot_pipe,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(27), 2,
      sym_literal,
      sym_word,
    STATE(52), 2,
      sym__expr_comma_group,
      sym_call,
    STATE(23), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
  [224] = 2,
    ACTIONS(50), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(48), 12,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_binding_token1,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_word,
  [243] = 2,
    ACTIONS(54), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(52), 12,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_binding_token1,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_word,
  [262] = 10,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      aux_sym_call_repeat1,
    STATE(30), 1,
      sym_no_space_call,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(60), 1,
      sym__expr_dot_pipe,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(33), 2,
      sym_literal,
      sym_word,
    STATE(41), 2,
      sym__expr_call,
      sym_dot_pipe,
    STATE(25), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
  [297] = 8,
    ACTIONS(62), 1,
      aux_sym_binding_token1,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(70), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(58), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(60), 2,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [328] = 7,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(70), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(58), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(60), 2,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [356] = 7,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(70), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(58), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(60), 2,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [384] = 6,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(70), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(58), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(60), 2,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(64), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [410] = 2,
    ACTIONS(76), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(74), 11,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_word,
  [428] = 5,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(70), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(58), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_word,
  [452] = 4,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(70), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(78), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(66), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_word,
  [474] = 6,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(60), 3,
      anon_sym_LBRACE,
      sym_literal,
      sym_word,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [499] = 2,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 11,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      sym_literal,
      sym_word,
  [516] = 3,
    ACTIONS(86), 1,
      anon_sym_DOT,
    STATE(29), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(84), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_literal,
      sym_word,
  [535] = 4,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_literal,
      sym_word,
  [556] = 3,
    ACTIONS(91), 1,
      anon_sym_DOT,
    STATE(29), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_literal,
      sym_word,
  [575] = 2,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    ACTIONS(93), 11,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      sym_literal,
      sym_word,
  [592] = 3,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_literal,
      sym_word,
  [611] = 5,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(60), 3,
      anon_sym_LBRACE,
      sym_literal,
      sym_word,
    ACTIONS(64), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [634] = 6,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(66), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_LPAREN2,
    ACTIONS(60), 3,
      anon_sym_LBRACE,
      sym_literal,
      sym_word,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [659] = 8,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_no_space_call,
    STATE(38), 1,
      sym__expr_dot_pipe,
    STATE(59), 1,
      sym__expr_no_space_call,
    STATE(61), 1,
      sym__expr_call_on_literal,
    ACTIONS(97), 2,
      sym_literal,
      sym_word,
    STATE(26), 3,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
  [687] = 3,
    STATE(37), 1,
      aux_sym__break,
    ACTIONS(101), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_literal,
      sym_word,
  [705] = 1,
    ACTIONS(84), 11,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_literal,
      sym_word,
  [719] = 3,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_comma_group_repeat1,
    ACTIONS(104), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_literal,
      sym_word,
  [737] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(60), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_literal,
      sym_word,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [754] = 1,
    ACTIONS(109), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_literal,
      sym_word,
  [767] = 2,
    ACTIONS(60), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_literal,
      sym_word,
    ACTIONS(64), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [782] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(60), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_literal,
      sym_word,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [799] = 4,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comma_group_repeat1,
    STATE(44), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [816] = 4,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_comma_group_repeat1,
    STATE(44), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(29), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [833] = 4,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_comma_group_repeat1,
    STATE(44), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [850] = 4,
    STATE(4), 1,
      aux_sym__break,
    STATE(48), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(122), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [866] = 4,
    STATE(3), 1,
      aux_sym__break,
    STATE(49), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(124), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [882] = 4,
    STATE(8), 1,
      aux_sym__break,
    STATE(49), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(128), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [898] = 4,
    STATE(2), 1,
      aux_sym__break,
    STATE(51), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(133), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [914] = 4,
    STATE(4), 1,
      aux_sym__break,
    STATE(49), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(122), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [930] = 1,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [939] = 2,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [950] = 2,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [961] = 1,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [969] = 1,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [977] = 3,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comma_group_repeat1,
    STATE(45), 1,
      aux_sym_comma_group_repeat2,
  [987] = 3,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_comma_group_repeat1,
    STATE(46), 1,
      aux_sym_comma_group_repeat2,
  [997] = 2,
    ACTIONS(139), 1,
      anon_sym_LPAREN2,
    STATE(32), 1,
      sym_immediate_group,
  [1004] = 2,
    ACTIONS(91), 1,
      anon_sym_DOT,
    STATE(31), 1,
      aux_sym_dot_pipe_repeat1,
  [1011] = 1,
    ACTIONS(141), 1,
      aux_sym_call_on_literal_token1,
  [1015] = 1,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
  [1019] = 1,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
  [1023] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [1027] = 1,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
  [1031] = 1,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 43,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 136,
  [SMALL_STATE(16)] = 180,
  [SMALL_STATE(17)] = 224,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 262,
  [SMALL_STATE(20)] = 297,
  [SMALL_STATE(21)] = 328,
  [SMALL_STATE(22)] = 356,
  [SMALL_STATE(23)] = 384,
  [SMALL_STATE(24)] = 410,
  [SMALL_STATE(25)] = 428,
  [SMALL_STATE(26)] = 452,
  [SMALL_STATE(27)] = 474,
  [SMALL_STATE(28)] = 499,
  [SMALL_STATE(29)] = 516,
  [SMALL_STATE(30)] = 535,
  [SMALL_STATE(31)] = 556,
  [SMALL_STATE(32)] = 575,
  [SMALL_STATE(33)] = 592,
  [SMALL_STATE(34)] = 611,
  [SMALL_STATE(35)] = 634,
  [SMALL_STATE(36)] = 659,
  [SMALL_STATE(37)] = 687,
  [SMALL_STATE(38)] = 705,
  [SMALL_STATE(39)] = 719,
  [SMALL_STATE(40)] = 737,
  [SMALL_STATE(41)] = 754,
  [SMALL_STATE(42)] = 767,
  [SMALL_STATE(43)] = 782,
  [SMALL_STATE(44)] = 799,
  [SMALL_STATE(45)] = 816,
  [SMALL_STATE(46)] = 833,
  [SMALL_STATE(47)] = 850,
  [SMALL_STATE(48)] = 866,
  [SMALL_STATE(49)] = 882,
  [SMALL_STATE(50)] = 898,
  [SMALL_STATE(51)] = 914,
  [SMALL_STATE(52)] = 930,
  [SMALL_STATE(53)] = 939,
  [SMALL_STATE(54)] = 950,
  [SMALL_STATE(55)] = 961,
  [SMALL_STATE(56)] = 969,
  [SMALL_STATE(57)] = 977,
  [SMALL_STATE(58)] = 987,
  [SMALL_STATE(59)] = 997,
  [SMALL_STATE(60)] = 1004,
  [SMALL_STATE(61)] = 1011,
  [SMALL_STATE(62)] = 1015,
  [SMALL_STATE(63)] = 1019,
  [SMALL_STATE(64)] = 1023,
  [SMALL_STATE(65)] = 1027,
  [SMALL_STATE(66)] = 1031,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(25),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe, 3),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 3),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr_call, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_call, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_comma_group, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_dot_pipe, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_no_space_call, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_call_on_literal, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_binding, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_on_literal, 2, .production_id = 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_on_literal, 2, .production_id = 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr_dot_pipe, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_immediate_group, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_immediate_group, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2), SHIFT_REPEAT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dot_pipe, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_no_space_call, 2, .production_id = 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_no_space_call, 2, .production_id = 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__break, 2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__break, 2), SHIFT_REPEAT(37),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat1, 2),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat1, 2), SHIFT_REPEAT(39),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2), SHIFT_REPEAT(16),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(8),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, .production_id = 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [147] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bismuth(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_tree_sitter_word,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
