#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 5

enum {
  sym_tree_sitter_word = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COLON = 8,
  aux_sym_binding_token1 = 9,
  anon_sym_COMMA = 10,
  anon_sym_DOT = 11,
  anon_sym_LPAREN2 = 12,
  aux_sym_call_on_literal_token1 = 13,
  sym_string_block = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  sym_literal = 17,
  sym_word = 18,
  sym_symbol = 19,
  sym_source_file = 20,
  sym__sequence = 21,
  aux_sym__break = 22,
  sym__expr = 23,
  sym_group = 24,
  sym_pipe = 25,
  sym_tail_dedent = 26,
  sym__tail_dedent_expr = 27,
  sym_binding = 28,
  sym__expr_binding = 29,
  sym_comma_group = 30,
  sym__expr_comma_group = 31,
  sym_infix_call = 32,
  sym__expr_infix_call = 33,
  sym_call = 34,
  sym__expr_call = 35,
  sym_dot_pipe = 36,
  sym__expr_dot_pipe = 37,
  sym_no_space_call = 38,
  sym__expr_no_space_call = 39,
  sym_immediate_group = 40,
  sym_call_on_literal = 41,
  sym__expr_call_on_literal = 42,
  sym_string = 43,
  aux_sym__sequence_repeat1 = 44,
  aux_sym_comma_group_repeat1 = 45,
  aux_sym_comma_group_repeat2 = 46,
  aux_sym_call_repeat1 = 47,
  aux_sym_dot_pipe_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_tree_sitter_word] = "tree_sitter_word",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [aux_sym_binding_token1] = "binding_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN2] = "(",
  [aux_sym_call_on_literal_token1] = "literal",
  [sym_string_block] = "string",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_literal] = "literal",
  [sym_word] = "word",
  [sym_symbol] = "symbol",
  [sym_source_file] = "source_file",
  [sym__sequence] = "_sequence",
  [aux_sym__break] = "_break",
  [sym__expr] = "_expr",
  [sym_group] = "group",
  [sym_pipe] = "pipe",
  [sym_tail_dedent] = "tail_dedent",
  [sym__tail_dedent_expr] = "_tail_dedent_expr",
  [sym_binding] = "binding",
  [sym__expr_binding] = "_expr_binding",
  [sym_comma_group] = "group",
  [sym__expr_comma_group] = "_expr_comma_group",
  [sym_infix_call] = "call",
  [sym__expr_infix_call] = "_expr_infix_call",
  [sym_call] = "call",
  [sym__expr_call] = "_expr_call",
  [sym_dot_pipe] = "pipe",
  [sym__expr_dot_pipe] = "_expr_dot_pipe",
  [sym_no_space_call] = "call",
  [sym__expr_no_space_call] = "_expr_no_space_call",
  [sym_immediate_group] = "group",
  [sym_call_on_literal] = "call",
  [sym__expr_call_on_literal] = "_expr_call_on_literal",
  [sym_string] = "string",
  [aux_sym__sequence_repeat1] = "_sequence_repeat1",
  [aux_sym_comma_group_repeat1] = "comma_group_repeat1",
  [aux_sym_comma_group_repeat2] = "comma_group_repeat2",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_dot_pipe_repeat1] = "dot_pipe_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_tree_sitter_word] = sym_tree_sitter_word,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_binding_token1] = aux_sym_binding_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [aux_sym_call_on_literal_token1] = sym_literal,
  [sym_string_block] = sym_string,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_literal] = sym_literal,
  [sym_word] = sym_word,
  [sym_symbol] = sym_symbol,
  [sym_source_file] = sym_source_file,
  [sym__sequence] = sym__sequence,
  [aux_sym__break] = aux_sym__break,
  [sym__expr] = sym__expr,
  [sym_group] = sym_group,
  [sym_pipe] = sym_pipe,
  [sym_tail_dedent] = sym_tail_dedent,
  [sym__tail_dedent_expr] = sym__tail_dedent_expr,
  [sym_binding] = sym_binding,
  [sym__expr_binding] = sym__expr_binding,
  [sym_comma_group] = sym_group,
  [sym__expr_comma_group] = sym__expr_comma_group,
  [sym_infix_call] = sym_call,
  [sym__expr_infix_call] = sym__expr_infix_call,
  [sym_call] = sym_call,
  [sym__expr_call] = sym__expr_call,
  [sym_dot_pipe] = sym_pipe,
  [sym__expr_dot_pipe] = sym__expr_dot_pipe,
  [sym_no_space_call] = sym_call,
  [sym__expr_no_space_call] = sym__expr_no_space_call,
  [sym_immediate_group] = sym_group,
  [sym_call_on_literal] = sym_call,
  [sym__expr_call_on_literal] = sym__expr_call_on_literal,
  [sym_string] = sym_string,
  [aux_sym__sequence_repeat1] = aux_sym__sequence_repeat1,
  [aux_sym_comma_group_repeat1] = aux_sym_comma_group_repeat1,
  [aux_sym_comma_group_repeat2] = aux_sym_comma_group_repeat2,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_dot_pipe_repeat1] = aux_sym_dot_pipe_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_tree_sitter_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_binding_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_call_on_literal_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_string_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sequence] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__break] = {
    .visible = false,
    .named = false,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_tail_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym__tail_dedent_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_binding] = {
    .visible = false,
    .named = true,
  },
  [sym_comma_group] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_comma_group] = {
    .visible = false,
    .named = true,
  },
  [sym_infix_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_infix_call] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_call] = {
    .visible = false,
    .named = true,
  },
  [sym_dot_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_dot_pipe] = {
    .visible = false,
    .named = true,
  },
  [sym_no_space_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_no_space_call] = {
    .visible = false,
    .named = true,
  },
  [sym_immediate_group] = {
    .visible = true,
    .named = true,
  },
  [sym_call_on_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_call_on_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_group_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dot_pipe_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_fn = 1,
  field_id = 2,
  field_input = 3,
  field_left = 4,
  field_right = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fn] = "fn",
  [field_id] = "id",
  [field_input] = "input",
  [field_left] = "left",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_fn, 0},
    {field_input, 1},
  [2] =
    {field_id, 0},
    {field_value, 2},
  [4] =
    {field_fn, 1},
    {field_left, 0},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_group,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_call_repeat1, 2,
    aux_sym_call_repeat1,
    sym_group,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 5,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 13,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 16,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 21,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 27,
  [36] = 29,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 44,
  [52] = 52,
  [53] = 40,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 65,
  [70] = 70,
  [71] = 66,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 88,
  [90] = 87,
  [91] = 91,
  [92] = 92,
  [93] = 92,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 96,
  [104] = 95,
  [105] = 105,
  [106] = 98,
};

static inline bool anon_sym_LF_character_set_1(int32_t c) {
  return (c < 8232
    ? (c < 160
      ? (c < ' '
        ? (c >= '\t' && c <= '\r')
        : c <= ' ')
      : (c <= 160 || (c < 8192
        ? c == 5760
        : c <= 8202)))
    : (c <= 8233 || (c < 12288
      ? (c < 8287
        ? c == 8239
        : c <= 8287)
      : (c <= 12288 || c == 65279))));
}

static inline bool sym_string_block_character_set_1(int32_t c) {
  return (c < 8192
    ? (c < ' '
      ? (c < 11
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || (c < 5760
        ? c == 160
        : c <= 5760)))
    : (c <= 8202 || (c < 8287
      ? (c < 8239
        ? (c >= 8232 && c <= 8233)
        : c <= 8239)
      : (c <= 8287 || (c < 65279
        ? c == 12288
        : c <= 65279)))));
}

static inline bool sym_symbol_character_set_1(int32_t c) {
  return (c < '<'
    ? (c < '*'
      ? (c < '#'
        ? c == '!'
        : c <= '&')
      : (c <= '+' || (c < '/'
        ? c == '-'
        : c <= '/')))
    : (c <= '@' || (c < '|'
      ? (c < '^'
        ? c == '\\'
        : c <= '^')
      : (c <= '|' || c == '~'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(6)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '`') ADVANCE(23);
      if (sym_string_block_character_set_1(lookahead)) ADVANCE(1);
      END_STATE();
    case 2:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(6)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 3:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(5)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 4:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(5)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(5)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '`') ADVANCE(23);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(6)
      if (('0' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (sym_string_block_character_set_1(lookahead)) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (sym_string_block_character_set_1(lookahead)) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_binding_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_call_on_literal_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string_block);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (sym_string_block_character_set_1(lookahead)) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_symbol);
      if (sym_symbol_character_set_1(lookahead)) ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 5},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 25},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 5},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_tree_sitter_word] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_binding_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [aux_sym_call_on_literal_token1] = ACTIONS(1),
    [sym_string_block] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(105),
    [sym__sequence] = STATE(102),
    [aux_sym__break] = STATE(11),
    [sym__expr] = STATE(79),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(79),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(79),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [2] = {
    [aux_sym__break] = STATE(63),
    [sym__expr] = STATE(84),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(84),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(84),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [3] = {
    [aux_sym__break] = STATE(63),
    [sym__expr] = STATE(84),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(84),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(84),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [4] = {
    [aux_sym__break] = STATE(63),
    [sym__expr] = STATE(84),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(84),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(84),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [5] = {
    [sym__sequence] = STATE(98),
    [aux_sym__break] = STATE(11),
    [sym__expr] = STATE(79),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(79),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(79),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [6] = {
    [sym__sequence] = STATE(96),
    [aux_sym__break] = STATE(11),
    [sym__expr] = STATE(79),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(79),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(79),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [7] = {
    [sym__sequence] = STATE(100),
    [aux_sym__break] = STATE(11),
    [sym__expr] = STATE(79),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(79),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(79),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [8] = {
    [sym__sequence] = STATE(106),
    [aux_sym__break] = STATE(11),
    [sym__expr] = STATE(79),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(79),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(79),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [9] = {
    [sym__sequence] = STATE(103),
    [aux_sym__break] = STATE(11),
    [sym__expr] = STATE(79),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(79),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(79),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [10] = {
    [aux_sym__break] = STATE(63),
    [sym__expr] = STATE(84),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(84),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(84),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [11] = {
    [aux_sym__break] = STATE(63),
    [sym__expr] = STATE(73),
    [sym_group] = STATE(26),
    [sym_pipe] = STATE(26),
    [sym_tail_dedent] = STATE(73),
    [sym__tail_dedent_expr] = STATE(99),
    [sym_binding] = STATE(73),
    [sym_comma_group] = STATE(82),
    [sym__expr_comma_group] = STATE(90),
    [sym_infix_call] = STATE(80),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(72),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(61),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(42),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(34),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(34),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_string_block] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [sym_word] = ACTIONS(17),
  },
  [12] = {
    [sym_group] = STATE(39),
    [sym_pipe] = STATE(39),
    [sym__expr_comma_group] = STATE(78),
    [sym_infix_call] = STATE(78),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(70),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(60),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(46),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(39),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(39),
    [aux_sym_comma_group_repeat1] = STATE(59),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym_string_block] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(37),
    [sym_word] = ACTIONS(37),
  },
  [13] = {
    [sym_group] = STATE(39),
    [sym_pipe] = STATE(39),
    [sym__expr_comma_group] = STATE(78),
    [sym_infix_call] = STATE(78),
    [sym__expr_infix_call] = STATE(95),
    [sym_call] = STATE(70),
    [sym__expr_call] = STATE(32),
    [sym_dot_pipe] = STATE(60),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(46),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(39),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(39),
    [aux_sym_comma_group_repeat1] = STATE(59),
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_LF] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym_string_block] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(37),
    [sym_word] = ACTIONS(37),
  },
  [14] = {
    [sym_group] = STATE(39),
    [sym_pipe] = STATE(39),
    [sym__expr_comma_group] = STATE(78),
    [sym_infix_call] = STATE(78),
    [sym__expr_infix_call] = STATE(104),
    [sym_call] = STATE(70),
    [sym__expr_call] = STATE(33),
    [sym_dot_pipe] = STATE(60),
    [sym__expr_dot_pipe] = STATE(93),
    [sym_no_space_call] = STATE(46),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(39),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(39),
    [aux_sym_comma_group_repeat1] = STATE(59),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LF] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym_string_block] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(37),
    [sym_word] = ACTIONS(37),
  },
  [15] = {
    [sym_group] = STATE(39),
    [sym_pipe] = STATE(39),
    [sym__expr_comma_group] = STATE(78),
    [sym_infix_call] = STATE(78),
    [sym__expr_infix_call] = STATE(104),
    [sym_call] = STATE(70),
    [sym__expr_call] = STATE(33),
    [sym_dot_pipe] = STATE(60),
    [sym__expr_dot_pipe] = STATE(93),
    [sym_no_space_call] = STATE(46),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(39),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(39),
    [aux_sym_comma_group_repeat1] = STATE(59),
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_LF] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym_string_block] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(37),
    [sym_word] = ACTIONS(37),
  },
  [16] = {
    [sym_group] = STATE(38),
    [sym_pipe] = STATE(38),
    [sym__expr_call] = STATE(56),
    [sym_dot_pipe] = STATE(56),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(48),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(38),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(38),
    [aux_sym_call_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_LF] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_COLON] = ACTIONS(51),
    [anon_sym_COMMA] = ACTIONS(43),
    [sym_string_block] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(56),
    [sym_literal] = ACTIONS(53),
    [sym_word] = ACTIONS(53),
    [sym_symbol] = ACTIONS(43),
  },
  [17] = {
    [sym_group] = STATE(38),
    [sym_pipe] = STATE(38),
    [sym__expr_call] = STATE(56),
    [sym_dot_pipe] = STATE(56),
    [sym__expr_dot_pipe] = STATE(92),
    [sym_no_space_call] = STATE(48),
    [sym__expr_no_space_call] = STATE(91),
    [sym_call_on_literal] = STATE(38),
    [sym__expr_call_on_literal] = STATE(97),
    [sym_string] = STATE(38),
    [aux_sym_call_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(61),
    [anon_sym_COMMA] = ACTIONS(59),
    [sym_string_block] = ACTIONS(63),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_literal] = ACTIONS(63),
    [sym_word] = ACTIONS(63),
    [sym_symbol] = ACTIONS(59),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      aux_sym_call_repeat1,
    STATE(48), 1,
      sym_no_space_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(56), 2,
      sym__expr_call,
      sym_dot_pipe,
    ACTIONS(63), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(38), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_symbol,
  [49] = 12,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      aux_sym_call_repeat1,
    STATE(48), 1,
      sym_no_space_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(56), 2,
      sym__expr_call,
      sym_dot_pipe,
    ACTIONS(53), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(38), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
    ACTIONS(43), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_symbol,
  [98] = 18,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_comma_group_repeat1,
    STATE(33), 1,
      sym__expr_call,
    STATE(55), 1,
      sym_no_space_call,
    STATE(62), 1,
      sym_dot_pipe,
    STATE(75), 1,
      sym_call,
    STATE(83), 1,
      sym_infix_call,
    STATE(87), 1,
      sym__expr_comma_group,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(104), 1,
      sym__expr_infix_call,
    STATE(85), 2,
      sym__expr_binding,
      sym_comma_group,
    ACTIONS(73), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(50), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [159] = 16,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym__expr_call,
    STATE(46), 1,
      sym_no_space_call,
    STATE(59), 1,
      aux_sym_comma_group_repeat1,
    STATE(60), 1,
      sym_dot_pipe,
    STATE(70), 1,
      sym_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(104), 1,
      sym__expr_infix_call,
    STATE(78), 2,
      sym__expr_comma_group,
      sym_infix_call,
    ACTIONS(37), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(39), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [214] = 16,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym__expr_call,
    STATE(46), 1,
      sym_no_space_call,
    STATE(59), 1,
      aux_sym_comma_group_repeat1,
    STATE(60), 1,
      sym_dot_pipe,
    STATE(70), 1,
      sym_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(104), 1,
      sym__expr_infix_call,
    STATE(89), 2,
      sym__expr_comma_group,
      sym_infix_call,
    ACTIONS(37), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(39), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [269] = 16,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym__expr_call,
    STATE(46), 1,
      sym_no_space_call,
    STATE(59), 1,
      aux_sym_comma_group_repeat1,
    STATE(60), 1,
      sym_dot_pipe,
    STATE(70), 1,
      sym_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(104), 1,
      sym__expr_infix_call,
    STATE(88), 2,
      sym__expr_comma_group,
      sym_infix_call,
    ACTIONS(37), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(39), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [324] = 16,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      sym__expr_call,
    STATE(46), 1,
      sym_no_space_call,
    STATE(59), 1,
      aux_sym_comma_group_repeat1,
    STATE(60), 1,
      sym_dot_pipe,
    STATE(70), 1,
      sym_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(92), 1,
      sym__expr_dot_pipe,
    STATE(95), 1,
      sym__expr_infix_call,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(78), 2,
      sym__expr_comma_group,
      sym_infix_call,
    ACTIONS(37), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(39), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [379] = 12,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym__expr_call,
    STATE(54), 1,
      sym_no_space_call,
    STATE(64), 1,
      sym_dot_pipe,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(74), 2,
      sym__expr_infix_call,
      sym_call,
    ACTIONS(75), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(47), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [422] = 10,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(85), 1,
      aux_sym_binding_token1,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(81), 4,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [461] = 2,
    ACTIONS(99), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(97), 15,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_binding_token1,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [484] = 12,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym__expr_call,
    STATE(54), 1,
      sym_no_space_call,
    STATE(64), 1,
      sym_dot_pipe,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(92), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(74), 2,
      sym__expr_infix_call,
      sym_call,
    ACTIONS(75), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(47), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [527] = 2,
    ACTIONS(103), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(101), 15,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_binding_token1,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [550] = 2,
    ACTIONS(107), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(105), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [572] = 4,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(109), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(89), 12,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [598] = 11,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      aux_sym_call_repeat1,
    STATE(48), 1,
      sym_no_space_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(92), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(56), 2,
      sym__expr_call,
      sym_dot_pipe,
    ACTIONS(63), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(38), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [638] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      aux_sym_call_repeat1,
    STATE(48), 1,
      sym_no_space_call,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(93), 1,
      sym__expr_dot_pipe,
    STATE(97), 1,
      sym__expr_call_on_literal,
    STATE(56), 2,
      sym__expr_call,
      sym_dot_pipe,
    ACTIONS(63), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(38), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [678] = 9,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(81), 4,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [714] = 2,
    ACTIONS(99), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(97), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [736] = 2,
    ACTIONS(103), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(101), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [758] = 2,
    ACTIONS(113), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(111), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      aux_sym_call_on_literal_token1,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [780] = 5,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(79), 3,
      anon_sym_LPAREN,
      anon_sym_COLON,
      sym_literal,
    ACTIONS(81), 11,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
      sym_symbol,
  [808] = 8,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(115), 1,
      anon_sym_COLON,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(81), 4,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [842] = 4,
    ACTIONS(119), 1,
      anon_sym_COLON,
    ACTIONS(121), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(117), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [867] = 2,
    ACTIONS(125), 2,
      anon_sym_LPAREN,
      anon_sym_COLON,
    ACTIONS(123), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [888] = 8,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(81), 5,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
  [921] = 2,
    ACTIONS(129), 2,
      anon_sym_LPAREN,
      anon_sym_COLON,
    ACTIONS(127), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_LPAREN2,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [942] = 4,
    ACTIONS(133), 1,
      anon_sym_COLON,
    ACTIONS(135), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(131), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [967] = 3,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(109), 2,
      anon_sym_LPAREN,
      anon_sym_COLON,
    ACTIONS(89), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [990] = 7,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(115), 1,
      anon_sym_COLON,
    ACTIONS(81), 5,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1021] = 7,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(81), 4,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1052] = 4,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      anon_sym_COLON,
    ACTIONS(81), 12,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [1077] = 8,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(81), 4,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1110] = 8,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(93), 1,
      aux_sym_call_on_literal_token1,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(79), 2,
      anon_sym_LPAREN,
      sym_literal,
    ACTIONS(81), 4,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_word,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1143] = 3,
    ACTIONS(142), 1,
      anon_sym_DOT,
    STATE(51), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(131), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [1165] = 2,
    ACTIONS(133), 1,
      anon_sym_COLON,
    ACTIONS(131), 14,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [1185] = 3,
    ACTIONS(145), 1,
      anon_sym_DOT,
    STATE(51), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(117), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [1207] = 6,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(81), 5,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1235] = 7,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_LPAREN2,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(81), 5,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1265] = 2,
    ACTIONS(149), 1,
      anon_sym_COLON,
    ACTIONS(147), 13,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
      sym_symbol,
  [1284] = 9,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_no_space_call,
    STATE(52), 1,
      sym__expr_dot_pipe,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(97), 1,
      sym__expr_call_on_literal,
    ACTIONS(151), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(31), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [1317] = 9,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_no_space_call,
    STATE(52), 1,
      sym__expr_dot_pipe,
    STATE(91), 1,
      sym__expr_no_space_call,
    STATE(97), 1,
      sym__expr_call_on_literal,
    ACTIONS(151), 3,
      sym_string_block,
      sym_literal,
      sym_word,
    STATE(31), 4,
      sym_group,
      sym_pipe,
      sym_call_on_literal,
      sym_string,
  [1350] = 4,
    ACTIONS(155), 1,
      anon_sym_COLON,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_comma_group_repeat1,
    ACTIONS(153), 11,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
  [1373] = 4,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(115), 1,
      anon_sym_COLON,
    ACTIONS(81), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1396] = 5,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(81), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
  [1421] = 4,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(81), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
  [1443] = 3,
    STATE(63), 1,
      aux_sym__break,
    ACTIONS(162), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(160), 10,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
  [1463] = 3,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(81), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_string_block,
      anon_sym_DQUOTE,
      sym_literal,
      sym_word,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1483] = 4,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_comma_group_repeat1,
    STATE(66), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(27), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1501] = 4,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_comma_group_repeat1,
    STATE(66), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1519] = 4,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_comma_group_repeat1,
    STATE(66), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1537] = 4,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_comma_group_repeat1,
    STATE(71), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1554] = 4,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_comma_group_repeat1,
    STATE(71), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(27), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1571] = 2,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_COMMA,
  [1584] = 4,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_comma_group_repeat1,
    STATE(71), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1601] = 4,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(183), 1,
      anon_sym_COLON,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1618] = 4,
    STATE(4), 1,
      aux_sym__break,
    STATE(76), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(185), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1634] = 1,
    ACTIONS(187), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_COMMA,
  [1644] = 3,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      sym_symbol,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1658] = 4,
    STATE(3), 1,
      aux_sym__break,
    STATE(77), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(189), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1674] = 4,
    STATE(10), 1,
      aux_sym__break,
    STATE(77), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(193), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1690] = 1,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_COMMA,
  [1700] = 4,
    STATE(2), 1,
      aux_sym__break,
    STATE(81), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(198), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(196), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1716] = 3,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_COLON,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1730] = 4,
    STATE(4), 1,
      aux_sym__break,
    STATE(77), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(185), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1746] = 2,
    ACTIONS(183), 1,
      anon_sym_COLON,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1757] = 2,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1768] = 1,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1776] = 1,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1784] = 1,
    ACTIONS(202), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1792] = 3,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_comma_group_repeat1,
    STATE(68), 1,
      aux_sym_comma_group_repeat2,
  [1802] = 3,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_comma_group_repeat1,
    STATE(65), 1,
      aux_sym_comma_group_repeat2,
  [1812] = 3,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_comma_group_repeat1,
    STATE(69), 1,
      aux_sym_comma_group_repeat2,
  [1822] = 3,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_comma_group_repeat1,
    STATE(67), 1,
      aux_sym_comma_group_repeat2,
  [1832] = 2,
    ACTIONS(208), 1,
      anon_sym_LPAREN2,
    STATE(43), 1,
      sym_immediate_group,
  [1839] = 2,
    ACTIONS(121), 1,
      anon_sym_DOT,
    STATE(40), 1,
      aux_sym_dot_pipe_repeat1,
  [1846] = 2,
    ACTIONS(145), 1,
      anon_sym_DOT,
    STATE(53), 1,
      aux_sym_dot_pipe_repeat1,
  [1853] = 1,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
  [1857] = 1,
    ACTIONS(212), 1,
      sym_symbol,
  [1861] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
  [1865] = 1,
    ACTIONS(216), 1,
      aux_sym_call_on_literal_token1,
  [1869] = 1,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
  [1873] = 1,
    ACTIONS(220), 1,
      anon_sym_COLON,
  [1877] = 1,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
  [1881] = 1,
    ACTIONS(224), 1,
      aux_sym_string_token1,
  [1885] = 1,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
  [1889] = 1,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
  [1893] = 1,
    ACTIONS(230), 1,
      sym_symbol,
  [1897] = 1,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
  [1901] = 1,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
  [SMALL_STATE(19)] = 49,
  [SMALL_STATE(20)] = 98,
  [SMALL_STATE(21)] = 159,
  [SMALL_STATE(22)] = 214,
  [SMALL_STATE(23)] = 269,
  [SMALL_STATE(24)] = 324,
  [SMALL_STATE(25)] = 379,
  [SMALL_STATE(26)] = 422,
  [SMALL_STATE(27)] = 461,
  [SMALL_STATE(28)] = 484,
  [SMALL_STATE(29)] = 527,
  [SMALL_STATE(30)] = 550,
  [SMALL_STATE(31)] = 572,
  [SMALL_STATE(32)] = 598,
  [SMALL_STATE(33)] = 638,
  [SMALL_STATE(34)] = 678,
  [SMALL_STATE(35)] = 714,
  [SMALL_STATE(36)] = 736,
  [SMALL_STATE(37)] = 758,
  [SMALL_STATE(38)] = 780,
  [SMALL_STATE(39)] = 808,
  [SMALL_STATE(40)] = 842,
  [SMALL_STATE(41)] = 867,
  [SMALL_STATE(42)] = 888,
  [SMALL_STATE(43)] = 921,
  [SMALL_STATE(44)] = 942,
  [SMALL_STATE(45)] = 967,
  [SMALL_STATE(46)] = 990,
  [SMALL_STATE(47)] = 1021,
  [SMALL_STATE(48)] = 1052,
  [SMALL_STATE(49)] = 1077,
  [SMALL_STATE(50)] = 1110,
  [SMALL_STATE(51)] = 1143,
  [SMALL_STATE(52)] = 1165,
  [SMALL_STATE(53)] = 1185,
  [SMALL_STATE(54)] = 1207,
  [SMALL_STATE(55)] = 1235,
  [SMALL_STATE(56)] = 1265,
  [SMALL_STATE(57)] = 1284,
  [SMALL_STATE(58)] = 1317,
  [SMALL_STATE(59)] = 1350,
  [SMALL_STATE(60)] = 1373,
  [SMALL_STATE(61)] = 1396,
  [SMALL_STATE(62)] = 1421,
  [SMALL_STATE(63)] = 1443,
  [SMALL_STATE(64)] = 1463,
  [SMALL_STATE(65)] = 1483,
  [SMALL_STATE(66)] = 1501,
  [SMALL_STATE(67)] = 1519,
  [SMALL_STATE(68)] = 1537,
  [SMALL_STATE(69)] = 1554,
  [SMALL_STATE(70)] = 1571,
  [SMALL_STATE(71)] = 1584,
  [SMALL_STATE(72)] = 1601,
  [SMALL_STATE(73)] = 1618,
  [SMALL_STATE(74)] = 1634,
  [SMALL_STATE(75)] = 1644,
  [SMALL_STATE(76)] = 1658,
  [SMALL_STATE(77)] = 1674,
  [SMALL_STATE(78)] = 1690,
  [SMALL_STATE(79)] = 1700,
  [SMALL_STATE(80)] = 1716,
  [SMALL_STATE(81)] = 1730,
  [SMALL_STATE(82)] = 1746,
  [SMALL_STATE(83)] = 1757,
  [SMALL_STATE(84)] = 1768,
  [SMALL_STATE(85)] = 1776,
  [SMALL_STATE(86)] = 1784,
  [SMALL_STATE(87)] = 1792,
  [SMALL_STATE(88)] = 1802,
  [SMALL_STATE(89)] = 1812,
  [SMALL_STATE(90)] = 1822,
  [SMALL_STATE(91)] = 1832,
  [SMALL_STATE(92)] = 1839,
  [SMALL_STATE(93)] = 1846,
  [SMALL_STATE(94)] = 1853,
  [SMALL_STATE(95)] = 1857,
  [SMALL_STATE(96)] = 1861,
  [SMALL_STATE(97)] = 1865,
  [SMALL_STATE(98)] = 1869,
  [SMALL_STATE(99)] = 1873,
  [SMALL_STATE(100)] = 1877,
  [SMALL_STATE(101)] = 1881,
  [SMALL_STATE(102)] = 1885,
  [SMALL_STATE(103)] = 1889,
  [SMALL_STATE(104)] = 1893,
  [SMALL_STATE(105)] = 1897,
  [SMALL_STATE(106)] = 1901,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comma_group, 3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 4),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comma_group, 4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(8),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(38),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(101),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(5),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(6),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr_call, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_call, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__tail_dedent_expr, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_comma_group, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_dot_pipe, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_no_space_call, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_call_on_literal, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_infix_call, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_on_literal, 2, .production_id = 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_on_literal, 2, .production_id = 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr_dot_pipe, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr_comma_group, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dot_pipe, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dot_pipe, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_immediate_group, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_immediate_group, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_no_space_call, 2, .production_id = 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_no_space_call, 2, .production_id = 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dot_pipe_repeat1, 2),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2), SHIFT_REPEAT(57),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr_infix_call, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_binding, 1),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2), SHIFT_REPEAT(58),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_call_repeat1, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat1, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comma_group_repeat1, 2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat1, 2), SHIFT_REPEAT(59),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__break, 2),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__break, 2), SHIFT_REPEAT(63),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2), SHIFT_REPEAT(24),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2), SHIFT_REPEAT(21),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tail_dedent_expr, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_call, 3, .production_id = 4),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(10),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, .production_id = 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tail_dedent, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [232] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bismuth(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_tree_sitter_word,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
