#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 2

enum {
  sym_tree_sitter_word = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COMMA = 8,
  anon_sym_DOT = 9,
  sym_word = 10,
  sym_symbol = 11,
  sym__space = 12,
  sym_source_file = 13,
  sym__sequence = 14,
  aux_sym__break = 15,
  sym__expr = 16,
  sym_group = 17,
  sym_pipe = 18,
  sym_call = 19,
  sym__expr_call = 20,
  sym_comma_group = 21,
  sym__expr_comma_group = 22,
  sym_dot_pipe = 23,
  sym__expr_dot_pipe = 24,
  aux_sym__sequence_repeat1 = 25,
  aux_sym_call_repeat1 = 26,
  aux_sym_comma_group_repeat1 = 27,
  aux_sym_comma_group_repeat2 = 28,
  aux_sym_dot_pipe_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_tree_sitter_word] = "tree_sitter_word",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [sym_word] = "word",
  [sym_symbol] = "symbol",
  [sym__space] = "_space",
  [sym_source_file] = "source_file",
  [sym__sequence] = "_sequence",
  [aux_sym__break] = "_break",
  [sym__expr] = "_expr",
  [sym_group] = "group",
  [sym_pipe] = "pipe",
  [sym_call] = "call",
  [sym__expr_call] = "_expr_call",
  [sym_comma_group] = "group",
  [sym__expr_comma_group] = "_expr_comma_group",
  [sym_dot_pipe] = "pipe",
  [sym__expr_dot_pipe] = "_expr_dot_pipe",
  [aux_sym__sequence_repeat1] = "_sequence_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_comma_group_repeat1] = "comma_group_repeat1",
  [aux_sym_comma_group_repeat2] = "comma_group_repeat2",
  [aux_sym_dot_pipe_repeat1] = "dot_pipe_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_tree_sitter_word] = sym_tree_sitter_word,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_word] = sym_word,
  [sym_symbol] = sym_symbol,
  [sym__space] = sym__space,
  [sym_source_file] = sym_source_file,
  [sym__sequence] = sym__sequence,
  [aux_sym__break] = aux_sym__break,
  [sym__expr] = sym__expr,
  [sym_group] = sym_group,
  [sym_pipe] = sym_pipe,
  [sym_call] = sym_call,
  [sym__expr_call] = sym__expr_call,
  [sym_comma_group] = sym_group,
  [sym__expr_comma_group] = sym__expr_comma_group,
  [sym_dot_pipe] = sym_pipe,
  [sym__expr_dot_pipe] = sym__expr_dot_pipe,
  [aux_sym__sequence_repeat1] = aux_sym__sequence_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_comma_group_repeat1] = aux_sym_comma_group_repeat1,
  [aux_sym_comma_group_repeat2] = aux_sym_comma_group_repeat2,
  [aux_sym_dot_pipe_repeat1] = aux_sym_dot_pipe_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_tree_sitter_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sequence] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__break] = {
    .visible = false,
    .named = false,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_call] = {
    .visible = false,
    .named = true,
  },
  [sym_comma_group] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_comma_group] = {
    .visible = false,
    .named = true,
  },
  [sym_dot_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_dot_pipe] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_group_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dot_pipe_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_fn = 1,
  field_input = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fn] = "fn",
  [field_input] = "input",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_fn, 0},
    {field_input, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static inline bool sym_symbol_character_set_1(int32_t c) {
  return (c < '<'
    ? (c < '*'
      ? (c < '#'
        ? c == '!'
        : c <= '&')
      : (c <= '+' || (c < '/'
        ? c == '-'
        : c <= '/')))
    : (c <= '@' || (c < '|'
      ? (c < '^'
        ? c == '\\'
        : c <= '^')
      : (c <= '|' || c == '~'))));
}

static inline bool sym__space_character_set_1(int32_t c) {
  return (c < 8232
    ? (c < 160
      ? (c < ' '
        ? (c >= '\t' && c <= '\r')
        : c <= ' ')
      : (c <= 160 || (c < 8192
        ? c == 5760
        : c <= 8202)))
    : (c <= 8233 || (c < 12288
      ? (c < 8287
        ? c == 8239
        : c <= 8287)
      : (c <= 12288 || c == 65279))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == ',') ADVANCE(9);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ';') ADVANCE(4);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(12);
      if (sym__space_character_set_1(lookahead)) ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == ',') ADVANCE(9);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ';') ADVANCE(4);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (sym__space_character_set_1(lookahead)) ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_symbol);
      if (sym_symbol_character_set_1(lookahead)) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_tree_sitter_word] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym__space] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(46),
    [sym__sequence] = STATE(45),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(35),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(35),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [2] = {
    [aux_sym__break] = STATE(19),
    [sym__expr] = STATE(39),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(39),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [3] = {
    [aux_sym__break] = STATE(19),
    [sym__expr] = STATE(39),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(39),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [4] = {
    [aux_sym__break] = STATE(19),
    [sym__expr] = STATE(39),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(39),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [5] = {
    [sym__sequence] = STATE(44),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(35),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(35),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [6] = {
    [sym__sequence] = STATE(43),
    [aux_sym__break] = STATE(9),
    [sym__expr] = STATE(35),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(35),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [7] = {
    [sym_group] = STATE(22),
    [sym_pipe] = STATE(22),
    [sym_call] = STATE(37),
    [sym__expr_call] = STATE(26),
    [sym__expr_comma_group] = STATE(37),
    [sym_dot_pipe] = STATE(27),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LF] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(25),
    [sym_word] = ACTIONS(27),
    [sym__space] = ACTIONS(3),
  },
  [8] = {
    [aux_sym__break] = STATE(19),
    [sym__expr] = STATE(39),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(39),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [9] = {
    [aux_sym__break] = STATE(19),
    [sym__expr] = STATE(34),
    [sym_group] = STATE(21),
    [sym_pipe] = STATE(21),
    [sym_call] = STATE(38),
    [sym__expr_call] = STATE(26),
    [sym_comma_group] = STATE(34),
    [sym__expr_comma_group] = STATE(41),
    [sym_dot_pipe] = STATE(25),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(13),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_word] = ACTIONS(13),
    [sym__space] = ACTIONS(3),
  },
  [10] = {
    [sym_group] = STATE(22),
    [sym_pipe] = STATE(22),
    [sym_call] = STATE(37),
    [sym__expr_call] = STATE(26),
    [sym__expr_comma_group] = STATE(37),
    [sym_dot_pipe] = STATE(27),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_comma_group_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(25),
    [sym_word] = ACTIONS(27),
    [sym__space] = ACTIONS(3),
  },
  [11] = {
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym__expr_call] = STATE(12),
    [sym_dot_pipe] = STATE(12),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_call_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LF] = ACTIONS(31),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_word] = ACTIONS(33),
    [sym__space] = ACTIONS(3),
  },
  [12] = {
    [sym_group] = STATE(20),
    [sym_pipe] = STATE(20),
    [sym__expr_call] = STATE(12),
    [sym_dot_pipe] = STATE(12),
    [sym__expr_dot_pipe] = STATE(42),
    [aux_sym_call_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_LF] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(37),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(40),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym_word] = ACTIONS(43),
    [sym__space] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    ACTIONS(27), 1,
      sym_word,
    STATE(23), 1,
      aux_sym_comma_group_repeat1,
    STATE(26), 1,
      sym__expr_call,
    STATE(27), 1,
      sym_dot_pipe,
    STATE(42), 1,
      sym__expr_dot_pipe,
    STATE(22), 2,
      sym_group,
      sym_pipe,
    STATE(40), 2,
      sym_call,
      sym__expr_comma_group,
  [36] = 11,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    ACTIONS(27), 1,
      sym_word,
    STATE(23), 1,
      aux_sym_comma_group_repeat1,
    STATE(26), 1,
      sym__expr_call,
    STATE(27), 1,
      sym_dot_pipe,
    STATE(42), 1,
      sym__expr_dot_pipe,
    STATE(22), 2,
      sym_group,
      sym_pipe,
    STATE(37), 2,
      sym_call,
      sym__expr_comma_group,
  [72] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(48), 1,
      anon_sym_DOT,
    STATE(15), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(46), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_word,
  [93] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(53), 1,
      anon_sym_DOT,
    STATE(15), 1,
      aux_sym_dot_pipe_repeat1,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_word,
  [114] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(55), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_word,
  [130] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(46), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_word,
  [146] = 4,
    ACTIONS(3), 1,
      sym__space,
    STATE(19), 1,
      aux_sym__break,
    ACTIONS(59), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_word,
  [166] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(64), 1,
      anon_sym_DOT,
    ACTIONS(62), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_word,
  [184] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(64), 1,
      anon_sym_DOT,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    ACTIONS(62), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [206] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(64), 1,
      anon_sym_DOT,
    ACTIONS(62), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [226] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_comma_group_repeat1,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_word,
  [246] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DOT,
      sym_word,
  [262] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    ACTIONS(62), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [281] = 7,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      sym_word,
    STATE(42), 1,
      sym__expr_dot_pipe,
    STATE(20), 2,
      sym_group,
      sym_pipe,
    STATE(11), 3,
      sym__expr_call,
      sym_dot_pipe,
      aux_sym_call_repeat1,
  [306] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(62), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_word,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [323] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_comma_group_repeat1,
    STATE(29), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(29), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [343] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_comma_group_repeat1,
    STATE(29), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [363] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_comma_group_repeat1,
    STATE(29), 1,
      aux_sym_comma_group_repeat2,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [383] = 5,
    ACTIONS(3), 1,
      sym__space,
    STATE(8), 1,
      aux_sym__break,
    STATE(31), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(90), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [402] = 5,
    ACTIONS(3), 1,
      sym__space,
    STATE(3), 1,
      aux_sym__break,
    STATE(31), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(93), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [421] = 5,
    ACTIONS(3), 1,
      sym__space,
    STATE(4), 1,
      aux_sym__break,
    STATE(31), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(95), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [440] = 5,
    ACTIONS(3), 1,
      sym__space,
    STATE(4), 1,
      aux_sym__break,
    STATE(32), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(95), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [459] = 5,
    ACTIONS(3), 1,
      sym__space,
    STATE(2), 1,
      aux_sym__break,
    STATE(33), 1,
      aux_sym__sequence_repeat1,
    ACTIONS(99), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [478] = 5,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(101), 1,
      sym_word,
    STATE(18), 3,
      sym_group,
      sym_pipe,
      sym__expr_dot_pipe,
  [496] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [508] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [522] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [533] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_comma_group_repeat1,
    STATE(28), 1,
      aux_sym_comma_group_repeat2,
  [546] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_comma_group_repeat1,
    STATE(30), 1,
      aux_sym_comma_group_repeat2,
  [559] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(53), 1,
      anon_sym_DOT,
    STATE(16), 1,
      aux_sym_dot_pipe_repeat1,
  [569] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
  [576] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
  [583] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
  [590] = 2,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 36,
  [SMALL_STATE(15)] = 72,
  [SMALL_STATE(16)] = 93,
  [SMALL_STATE(17)] = 114,
  [SMALL_STATE(18)] = 130,
  [SMALL_STATE(19)] = 146,
  [SMALL_STATE(20)] = 166,
  [SMALL_STATE(21)] = 184,
  [SMALL_STATE(22)] = 206,
  [SMALL_STATE(23)] = 226,
  [SMALL_STATE(24)] = 246,
  [SMALL_STATE(25)] = 262,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 306,
  [SMALL_STATE(28)] = 323,
  [SMALL_STATE(29)] = 343,
  [SMALL_STATE(30)] = 363,
  [SMALL_STATE(31)] = 383,
  [SMALL_STATE(32)] = 402,
  [SMALL_STATE(33)] = 421,
  [SMALL_STATE(34)] = 440,
  [SMALL_STATE(35)] = 459,
  [SMALL_STATE(36)] = 478,
  [SMALL_STATE(37)] = 496,
  [SMALL_STATE(38)] = 508,
  [SMALL_STATE(39)] = 522,
  [SMALL_STATE(40)] = 533,
  [SMALL_STATE(41)] = 546,
  [SMALL_STATE(42)] = 559,
  [SMALL_STATE(43)] = 569,
  [SMALL_STATE(44)] = 576,
  [SMALL_STATE(45)] = 583,
  [SMALL_STATE(46)] = 590,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(5),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(20),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dot_pipe_repeat1, 2), SHIFT_REPEAT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dot_pipe, 2),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__break, 2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__break, 2), SHIFT_REPEAT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_call, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_dot_pipe, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr_comma_group, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat1, 2),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat1, 2), SHIFT_REPEAT(23),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_group_repeat2, 2), SHIFT_REPEAT(14),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_group, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sequence_repeat1, 2), SHIFT_REPEAT(8),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sequence, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [111] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_bismuth(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_tree_sitter_word,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
